### ISSUE TITLE
Add in letsencrypt deployment

### ISSUE THREAD

**Issue by tmbgreaves** [alan-turing-institute/binderhub-deploy#28]
Current deployments only support http; add in letsencrypt support. CONTACT_EMAIL is already in place in the config to support this.

**Comment by sgibson91** [comment]
So to use letsencrypt, the user will have to purchase a domain name and set an A record before running this container, correct?

**Comment by tmbgreaves** [comment]
They should be able to get one automatically from azure to start with, something like:

binderhubname.westeurope.cloudapp.azure.com

**Comment by tmbgreaves** [comment]
(At least, that's what I do at the moment for testing!)

**Comment by sgibson91** [comment]
Ah, ok. But this won't propagate to the Binder IP because that's an end-point of the Binder pod running in the cluster.

**Comment by sgibson91** [comment]
(I haven't set up HTTPS on my cluster, but trying to for my Binder landing page.)

**Comment by sgibson91** [comment]
So as of today, I enabled HTTPS on the private Turing BinderHub. This involved a transition from directly using the BinderHub chart to using a meta-chart with dependencies on BinderHub, nginx-ingress and cert-manager. I think enabling Let's Encrypt is potentially out-of-scope for this repo. Happy to discuss though.

See https://github.com/alan-turing-institute/hub23-deploy for my deployment.

**Comment by sgibson91** [comment]
We can install cert-manager as per these docs: https://binderhub.readthedocs.io/en/latest/https.html

**Comment by sgibson91** [comment]
### Update on status of PR #80 

Working through the following docs: https://discourse.jupyter.org/t/wip-documentation-about-cert-manager/2068

Currently, running deploy.sh will install nginx-ingress and cert-manager charts and the load balancer IP is saved to a variable called `LOAD_BALANCER_IP`: https://github.com/alan-turing-institute/binderhub-deploy/blob/933bef3624566185e55f3b133dbf9b466a767910/deploy.sh#L522

The next step will go between the following line and the `if` statement: https://github.com/alan-turing-institute/binderhub-deploy/blob/933bef3624566185e55f3b133dbf9b466a767910/deploy.sh#L545

This will be to use the Azure CLI to create domain name and A records (for `BINDER_HOST` and `HUB_HOST`) and point them both at the `LOAD_BALANCER_IP`.

Relevant Azure CLI docs are here:

- Create a DNS zone: https://docs.microsoft.com/en-us/cli/azure/network/dns/zone?view=azure-cli-latest#az-network-dns-zone-create
- Create an empty A record: https://docs.microsoft.com/en-us/cli/azure/network/dns/record-set/a?view=azure-cli-latest#az-network-dns-record-set-a-create
- Set an A record: https://docs.microsoft.com/en-us/cli/azure/network/dns/record-set/a?view=azure-cli-latest#az-network-dns-record-set-a-add-record

Possible blockers: When setting this up, I usually ask Turing IT to set an NS record. I don't know what that involves myself since it's a closed process.

cc: @casperOne Hopefully this is enough to get you started with figuring things out. Ping me if you have any questions!
